ERROR - 2024-04-22 20:24:33 --> mysqli_sql_exception: PROCEDURE biblioteca.eliminar_asiento_repetido does not exist in C:\xampp\htdocs\Bib\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\Bib\system\Database\MySQLi\Connection.php(306): mysqli->query('CALL eliminar_a...', 0)
#1 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('CALL eliminar_a...')
#2 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('CALL eliminar_a...')
#3 C:\xampp\htdocs\Bib\app\Models\Principal.php(121): CodeIgniter\Database\BaseConnection->query('CALL eliminar_a...', Array)
#4 C:\xampp\htdocs\Bib\app\Controllers\ControllerPrincipal.php(201): App\Models\Principal->validar2(Array)
#5 C:\xampp\htdocs\Bib\system\CodeIgniter.php(942): App\Controllers\ControllerPrincipal->Validar2('0219080032', 'A14')
#6 C:\xampp\htdocs\Bib\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControllerPrincipal))
#7 C:\xampp\htdocs\Bib\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Bib\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2024-04-22 20:27:23 --> mysqli_sql_exception: ocupado,A14 in C:\xampp\htdocs\Bib\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\Bib\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO asi...', 0)
#1 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO asi...')
#2 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO asi...')
#3 C:\xampp\htdocs\Bib\app\Models\Principal.php(110): CodeIgniter\Database\BaseConnection->query('INSERT INTO asi...', Array)
#4 C:\xampp\htdocs\Bib\app\Controllers\ControllerPrincipal.php(189): App\Models\Principal->ValidarAll(Array)
#5 C:\xampp\htdocs\Bib\system\CodeIgniter.php(942): App\Controllers\ControllerPrincipal->ValidarAll('0219080041', 'A14')
#6 C:\xampp\htdocs\Bib\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControllerPrincipal))
#7 C:\xampp\htdocs\Bib\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Bib\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2024-04-22 20:27:23 --> mysqli_sql_exception: PROCEDURE biblioteca.eliminar_asiento_repetido does not exist in C:\xampp\htdocs\Bib\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\Bib\system\Database\MySQLi\Connection.php(306): mysqli->query('CALL eliminar_a...', 0)
#1 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('CALL eliminar_a...')
#2 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('CALL eliminar_a...')
#3 C:\xampp\htdocs\Bib\app\Models\Principal.php(121): CodeIgniter\Database\BaseConnection->query('CALL eliminar_a...', Array)
#4 C:\xampp\htdocs\Bib\app\Controllers\ControllerPrincipal.php(201): App\Models\Principal->validar2(Array)
#5 C:\xampp\htdocs\Bib\system\CodeIgniter.php(942): App\Controllers\ControllerPrincipal->Validar2('0219080041', 'A14')
#6 C:\xampp\htdocs\Bib\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControllerPrincipal))
#7 C:\xampp\htdocs\Bib\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Bib\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2024-04-22 20:28:45 --> mysqli_sql_exception: PROCEDURE biblioteca.eliminar_asiento_repetido does not exist in C:\xampp\htdocs\Bib\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\Bib\system\Database\MySQLi\Connection.php(306): mysqli->query('CALL eliminar_a...', 0)
#1 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('CALL eliminar_a...')
#2 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('CALL eliminar_a...')
#3 C:\xampp\htdocs\Bib\app\Models\Principal.php(121): CodeIgniter\Database\BaseConnection->query('CALL eliminar_a...', Array)
#4 C:\xampp\htdocs\Bib\app\Controllers\ControllerPrincipal.php(201): App\Models\Principal->validar2(Array)
#5 C:\xampp\htdocs\Bib\system\CodeIgniter.php(942): App\Controllers\ControllerPrincipal->Validar2('0219080041', 'A14')
#6 C:\xampp\htdocs\Bib\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControllerPrincipal))
#7 C:\xampp\htdocs\Bib\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Bib\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2024-04-22 20:32:53 --> mysqli_sql_exception: PROCEDURE biblioteca.eliminar_asiento_repetido does not exist in C:\xampp\htdocs\Bib\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\Bib\system\Database\MySQLi\Connection.php(306): mysqli->query('CALL eliminar_a...', 0)
#1 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('CALL eliminar_a...')
#2 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('CALL eliminar_a...')
#3 C:\xampp\htdocs\Bib\app\Models\Principal.php(121): CodeIgniter\Database\BaseConnection->query('CALL eliminar_a...', Array)
#4 C:\xampp\htdocs\Bib\app\Controllers\ControllerPrincipal.php(201): App\Models\Principal->validar2(Array)
#5 C:\xampp\htdocs\Bib\system\CodeIgniter.php(942): App\Controllers\ControllerPrincipal->Validar2('0219080032', 'A6')
#6 C:\xampp\htdocs\Bib\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControllerPrincipal))
#7 C:\xampp\htdocs\Bib\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Bib\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2024-04-22 20:33:05 --> mysqli_sql_exception: PROCEDURE biblioteca.eliminar_asiento_repetido does not exist in C:\xampp\htdocs\Bib\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\Bib\system\Database\MySQLi\Connection.php(306): mysqli->query('CALL eliminar_a...', 0)
#1 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('CALL eliminar_a...')
#2 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('CALL eliminar_a...')
#3 C:\xampp\htdocs\Bib\app\Models\Principal.php(121): CodeIgniter\Database\BaseConnection->query('CALL eliminar_a...', Array)
#4 C:\xampp\htdocs\Bib\app\Controllers\ControllerPrincipal.php(201): App\Models\Principal->validar2(Array)
#5 C:\xampp\htdocs\Bib\system\CodeIgniter.php(942): App\Controllers\ControllerPrincipal->Validar2('0219080041', 'A14')
#6 C:\xampp\htdocs\Bib\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControllerPrincipal))
#7 C:\xampp\htdocs\Bib\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Bib\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2024-04-22 20:33:21 --> mysqli_sql_exception: PROCEDURE biblioteca.eliminar_asiento_repetido does not exist in C:\xampp\htdocs\Bib\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\Bib\system\Database\MySQLi\Connection.php(306): mysqli->query('CALL eliminar_a...', 0)
#1 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('CALL eliminar_a...')
#2 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('CALL eliminar_a...')
#3 C:\xampp\htdocs\Bib\app\Models\Principal.php(121): CodeIgniter\Database\BaseConnection->query('CALL eliminar_a...', Array)
#4 C:\xampp\htdocs\Bib\app\Controllers\ControllerPrincipal.php(201): App\Models\Principal->validar2(Array)
#5 C:\xampp\htdocs\Bib\system\CodeIgniter.php(942): App\Controllers\ControllerPrincipal->Validar2('0321140008', 'E20')
#6 C:\xampp\htdocs\Bib\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControllerPrincipal))
#7 C:\xampp\htdocs\Bib\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Bib\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2024-04-22 20:33:38 --> mysqli_sql_exception: PROCEDURE biblioteca.eliminar_asiento_repetido does not exist in C:\xampp\htdocs\Bib\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\Bib\system\Database\MySQLi\Connection.php(306): mysqli->query('CALL eliminar_a...', 0)
#1 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('CALL eliminar_a...')
#2 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('CALL eliminar_a...')
#3 C:\xampp\htdocs\Bib\app\Models\Principal.php(121): CodeIgniter\Database\BaseConnection->query('CALL eliminar_a...', Array)
#4 C:\xampp\htdocs\Bib\app\Controllers\ControllerPrincipal.php(201): App\Models\Principal->validar2(Array)
#5 C:\xampp\htdocs\Bib\system\CodeIgniter.php(942): App\Controllers\ControllerPrincipal->Validar2('0219080032', 'B6')
#6 C:\xampp\htdocs\Bib\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControllerPrincipal))
#7 C:\xampp\htdocs\Bib\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Bib\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2024-04-22 20:34:19 --> mysqli_sql_exception: PROCEDURE biblioteca.eliminar_asiento_repetido does not exist in C:\xampp\htdocs\Bib\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\Bib\system\Database\MySQLi\Connection.php(306): mysqli->query('CALL eliminar_a...', 0)
#1 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('CALL eliminar_a...')
#2 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('CALL eliminar_a...')
#3 C:\xampp\htdocs\Bib\app\Models\Principal.php(121): CodeIgniter\Database\BaseConnection->query('CALL eliminar_a...', Array)
#4 C:\xampp\htdocs\Bib\app\Controllers\ControllerPrincipal.php(201): App\Models\Principal->validar2(Array)
#5 C:\xampp\htdocs\Bib\system\CodeIgniter.php(942): App\Controllers\ControllerPrincipal->Validar2('0219080041', 'B5')
#6 C:\xampp\htdocs\Bib\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControllerPrincipal))
#7 C:\xampp\htdocs\Bib\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Bib\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2024-04-22 20:34:20 --> mysqli_sql_exception: PROCEDURE biblioteca.eliminar_asiento_repetido does not exist in C:\xampp\htdocs\Bib\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\Bib\system\Database\MySQLi\Connection.php(306): mysqli->query('CALL eliminar_a...', 0)
#1 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('CALL eliminar_a...')
#2 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('CALL eliminar_a...')
#3 C:\xampp\htdocs\Bib\app\Models\Principal.php(121): CodeIgniter\Database\BaseConnection->query('CALL eliminar_a...', Array)
#4 C:\xampp\htdocs\Bib\app\Controllers\ControllerPrincipal.php(201): App\Models\Principal->validar2(Array)
#5 C:\xampp\htdocs\Bib\system\CodeIgniter.php(942): App\Controllers\ControllerPrincipal->Validar2('0219080032', 'B5')
#6 C:\xampp\htdocs\Bib\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControllerPrincipal))
#7 C:\xampp\htdocs\Bib\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Bib\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2024-04-22 20:47:47 --> mysqli_sql_exception: ocupado,B5 in C:\xampp\htdocs\Bib\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\Bib\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO asi...', 0)
#1 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO asi...')
#2 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO asi...')
#3 C:\xampp\htdocs\Bib\app\Models\Principal.php(110): CodeIgniter\Database\BaseConnection->query('INSERT INTO asi...', Array)
#4 C:\xampp\htdocs\Bib\app\Controllers\ControllerPrincipal.php(189): App\Models\Principal->ValidarAll(Array)
#5 C:\xampp\htdocs\Bib\system\CodeIgniter.php(942): App\Controllers\ControllerPrincipal->ValidarAll('0321140010', 'B6')
#6 C:\xampp\htdocs\Bib\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControllerPrincipal))
#7 C:\xampp\htdocs\Bib\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Bib\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2024-04-22 20:48:01 --> mysqli_sql_exception: ocupado,B5 in C:\xampp\htdocs\Bib\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\Bib\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO asi...', 0)
#1 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO asi...')
#2 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO asi...')
#3 C:\xampp\htdocs\Bib\app\Models\Principal.php(110): CodeIgniter\Database\BaseConnection->query('INSERT INTO asi...', Array)
#4 C:\xampp\htdocs\Bib\app\Controllers\ControllerPrincipal.php(189): App\Models\Principal->ValidarAll(Array)
#5 C:\xampp\htdocs\Bib\system\CodeIgniter.php(942): App\Controllers\ControllerPrincipal->ValidarAll('0321140010', 'D14')
#6 C:\xampp\htdocs\Bib\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControllerPrincipal))
#7 C:\xampp\htdocs\Bib\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Bib\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
