ERROR - 2024-03-05 04:15:51 --> mysqli_sql_exception: El asiento ya está ocupado. Por favor, elige otro. in C:\xampp\htdocs\Bib\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\Bib\system\Database\MySQLi\Connection.php(306): mysqli->query('CALL InsertarRe...', 0)
#1 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('CALL InsertarRe...')
#2 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('CALL InsertarRe...')
#3 C:\xampp\htdocs\Bib\app\Models\Principal.php(15): CodeIgniter\Database\BaseConnection->query('CALL InsertarRe...', Array)
#4 C:\xampp\htdocs\Bib\app\Controllers\ControllerPrincipal.php(56): App\Models\Principal->insertarRecord(Array)
#5 C:\xampp\htdocs\Bib\system\CodeIgniter.php(942): App\Controllers\ControllerPrincipal->add2()
#6 C:\xampp\htdocs\Bib\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControllerPrincipal))
#7 C:\xampp\htdocs\Bib\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Bib\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2024-03-05 04:15:51 --> El asiento ya está ocupado. Por favor, elige otro.
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 APPPATH\Models\Principal.php(15): CodeIgniter\Database\BaseConnection->query('CALL InsertarRecord(?, ?)', [...])
 2 APPPATH\Controllers\ControllerPrincipal.php(56): App\Models\Principal->insertarRecord([...])
 3 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\ControllerPrincipal->add2()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControllerPrincipal))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-03-05 04:16:49 --> mysqli_sql_exception: El asiento ya está ocupado. Por favor, elige otro. in C:\xampp\htdocs\Bib\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\Bib\system\Database\MySQLi\Connection.php(306): mysqli->query('CALL InsertarRe...', 0)
#1 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('CALL InsertarRe...')
#2 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('CALL InsertarRe...')
#3 C:\xampp\htdocs\Bib\app\Models\Principal.php(15): CodeIgniter\Database\BaseConnection->query('CALL InsertarRe...', Array)
#4 C:\xampp\htdocs\Bib\app\Controllers\ControllerPrincipal.php(56): App\Models\Principal->insertarRecord(Array)
#5 C:\xampp\htdocs\Bib\system\CodeIgniter.php(942): App\Controllers\ControllerPrincipal->add2()
#6 C:\xampp\htdocs\Bib\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControllerPrincipal))
#7 C:\xampp\htdocs\Bib\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Bib\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2024-03-05 04:16:49 --> El asiento ya está ocupado. Por favor, elige otro.
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 APPPATH\Models\Principal.php(15): CodeIgniter\Database\BaseConnection->query('CALL InsertarRecord(?, ?)', [...])
 2 APPPATH\Controllers\ControllerPrincipal.php(56): App\Models\Principal->insertarRecord([...])
 3 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\ControllerPrincipal->add2()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControllerPrincipal))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-03-05 04:17:20 --> mysqli_sql_exception: El asiento ya está ocupado. Por favor, elige otro. in C:\xampp\htdocs\Bib\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\Bib\system\Database\MySQLi\Connection.php(306): mysqli->query('CALL InsertarRe...', 0)
#1 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('CALL InsertarRe...')
#2 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('CALL InsertarRe...')
#3 C:\xampp\htdocs\Bib\app\Models\Principal.php(15): CodeIgniter\Database\BaseConnection->query('CALL InsertarRe...', Array)
#4 C:\xampp\htdocs\Bib\app\Controllers\ControllerPrincipal.php(56): App\Models\Principal->insertarRecord(Array)
#5 C:\xampp\htdocs\Bib\system\CodeIgniter.php(942): App\Controllers\ControllerPrincipal->add2()
#6 C:\xampp\htdocs\Bib\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControllerPrincipal))
#7 C:\xampp\htdocs\Bib\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Bib\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2024-03-05 04:17:20 --> El asiento ya está ocupado. Por favor, elige otro.
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 APPPATH\Models\Principal.php(15): CodeIgniter\Database\BaseConnection->query('CALL InsertarRecord(?, ?)', [...])
 2 APPPATH\Controllers\ControllerPrincipal.php(56): App\Models\Principal->insertarRecord([...])
 3 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\ControllerPrincipal->add2()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControllerPrincipal))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-03-05 04:18:35 --> mysqli_sql_exception: El asiento ya está ocupado. Por favor, elige otro. in C:\xampp\htdocs\Bib\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\Bib\system\Database\MySQLi\Connection.php(306): mysqli->query('CALL InsertarRe...', 0)
#1 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('CALL InsertarRe...')
#2 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('CALL InsertarRe...')
#3 C:\xampp\htdocs\Bib\app\Models\Principal.php(15): CodeIgniter\Database\BaseConnection->query('CALL InsertarRe...', Array)
#4 C:\xampp\htdocs\Bib\app\Controllers\ControllerPrincipal.php(56): App\Models\Principal->insertarRecord(Array)
#5 C:\xampp\htdocs\Bib\system\CodeIgniter.php(942): App\Controllers\ControllerPrincipal->add2()
#6 C:\xampp\htdocs\Bib\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControllerPrincipal))
#7 C:\xampp\htdocs\Bib\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Bib\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2024-03-05 04:18:35 --> El asiento ya está ocupado. Por favor, elige otro.
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 APPPATH\Models\Principal.php(15): CodeIgniter\Database\BaseConnection->query('CALL InsertarRecord(?, ?)', [...])
 2 APPPATH\Controllers\ControllerPrincipal.php(56): App\Models\Principal->insertarRecord([...])
 3 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\ControllerPrincipal->add2()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControllerPrincipal))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-03-05 04:21:28 --> mysqli_sql_exception: Recursive limit 0 (as set by the max_sp_recursion_depth variable) was exceeded for routine InsertarRecord in C:\xampp\htdocs\Bib\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\Bib\system\Database\MySQLi\Connection.php(306): mysqli->query('CALL InsertarRe...', 0)
#1 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('CALL InsertarRe...')
#2 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('CALL InsertarRe...')
#3 C:\xampp\htdocs\Bib\app\Models\Principal.php(15): CodeIgniter\Database\BaseConnection->query('CALL InsertarRe...', Array)
#4 C:\xampp\htdocs\Bib\app\Controllers\ControllerPrincipal.php(56): App\Models\Principal->insertarRecord(Array)
#5 C:\xampp\htdocs\Bib\system\CodeIgniter.php(942): App\Controllers\ControllerPrincipal->add2()
#6 C:\xampp\htdocs\Bib\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControllerPrincipal))
#7 C:\xampp\htdocs\Bib\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Bib\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2024-03-05 04:21:28 --> Recursive limit 0 (as set by the max_sp_recursion_depth variable) was exceeded for routine InsertarRecord
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 APPPATH\Models\Principal.php(15): CodeIgniter\Database\BaseConnection->query('CALL InsertarRecord(?, ?)', [...])
 2 APPPATH\Controllers\ControllerPrincipal.php(56): App\Models\Principal->insertarRecord([...])
 3 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\ControllerPrincipal->add2()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControllerPrincipal))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-03-05 14:51:41 --> mysqli_sql_exception: Table 'biblioteca.asientos_computo' doesn't exist in C:\xampp\htdocs\Bib\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\Bib\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT a.NoCuen...', 0)
#1 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT a.NoCuen...')
#2 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT a.NoCuen...')
#3 C:\xampp\htdocs\Bib\app\Models\Principal.php(80): CodeIgniter\Database\BaseConnection->query('SELECT a.NoCuen...', Array)
#4 C:\xampp\htdocs\Bib\app\Controllers\ControllerPrincipal.php(86): App\Models\Principal->VerificarAsiento('0211980041')
#5 C:\xampp\htdocs\Bib\system\CodeIgniter.php(942): App\Controllers\ControllerPrincipal->verificar_asiento('0211980041')
#6 C:\xampp\htdocs\Bib\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControllerPrincipal))
#7 C:\xampp\htdocs\Bib\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Bib\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2024-03-05 14:51:41 --> Table 'biblioteca.asientos_computo' doesn't exist
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 APPPATH\Models\Principal.php(80): CodeIgniter\Database\BaseConnection->query('SELECT a.NoCuenta,
                                    a.Asiento AS AsientoTablaAsientos,
                                    ac.Asiento AS AsientoTablaAsientosComputo
                                FROM asientos a
                                    LEFT JOIN asientos_computo ac ON a.NoCuenta = ac.NoCuenta
                                WHERE a.NoCuenta = ?
                                UNION
                                SELECT ac.NoCuenta,
                                    a.Asiento AS AsientoTablaAsientos,
                                    ac.Asiento AS AsientoTablaAsientosComputo
                                FROM asientos a
                                    RIGHT JOIN asientos_computo ac ON a.NoCuenta = ac.NoCuenta
                                WHERE ac.NoCuenta = ?', [...])
 2 APPPATH\Controllers\ControllerPrincipal.php(86): App\Models\Principal->VerificarAsiento('0211980041')
 3 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\ControllerPrincipal->verificar_asiento('0211980041')
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControllerPrincipal))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-03-05 14:51:45 --> mysqli_sql_exception: Table 'biblioteca.asientos_computo' doesn't exist in C:\xampp\htdocs\Bib\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\Bib\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT a.NoCuen...', 0)
#1 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT a.NoCuen...')
#2 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT a.NoCuen...')
#3 C:\xampp\htdocs\Bib\app\Models\Principal.php(80): CodeIgniter\Database\BaseConnection->query('SELECT a.NoCuen...', Array)
#4 C:\xampp\htdocs\Bib\app\Controllers\ControllerPrincipal.php(86): App\Models\Principal->VerificarAsiento('00011980041')
#5 C:\xampp\htdocs\Bib\system\CodeIgniter.php(942): App\Controllers\ControllerPrincipal->verificar_asiento('00011980041')
#6 C:\xampp\htdocs\Bib\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControllerPrincipal))
#7 C:\xampp\htdocs\Bib\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Bib\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2024-03-05 14:51:45 --> Table 'biblioteca.asientos_computo' doesn't exist
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 APPPATH\Models\Principal.php(80): CodeIgniter\Database\BaseConnection->query('SELECT a.NoCuenta,
                                    a.Asiento AS AsientoTablaAsientos,
                                    ac.Asiento AS AsientoTablaAsientosComputo
                                FROM asientos a
                                    LEFT JOIN asientos_computo ac ON a.NoCuenta = ac.NoCuenta
                                WHERE a.NoCuenta = ?
                                UNION
                                SELECT ac.NoCuenta,
                                    a.Asiento AS AsientoTablaAsientos,
                                    ac.Asiento AS AsientoTablaAsientosComputo
                                FROM asientos a
                                    RIGHT JOIN asientos_computo ac ON a.NoCuenta = ac.NoCuenta
                                WHERE ac.NoCuenta = ?', [...])
 2 APPPATH\Controllers\ControllerPrincipal.php(86): App\Models\Principal->VerificarAsiento('00011980041')
 3 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\ControllerPrincipal->verificar_asiento('00011980041')
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControllerPrincipal))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-03-05 14:52:31 --> mysqli_sql_exception: Table 'biblioteca.asientos_computo' doesn't exist in C:\xampp\htdocs\Bib\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\Bib\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT a.NoCuen...', 0)
#1 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT a.NoCuen...')
#2 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT a.NoCuen...')
#3 C:\xampp\htdocs\Bib\app\Models\Principal.php(80): CodeIgniter\Database\BaseConnection->query('SELECT a.NoCuen...', Array)
#4 C:\xampp\htdocs\Bib\app\Controllers\ControllerPrincipal.php(86): App\Models\Principal->VerificarAsiento('0211980038')
#5 C:\xampp\htdocs\Bib\system\CodeIgniter.php(942): App\Controllers\ControllerPrincipal->verificar_asiento('0211980038')
#6 C:\xampp\htdocs\Bib\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControllerPrincipal))
#7 C:\xampp\htdocs\Bib\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Bib\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2024-03-05 14:52:31 --> Table 'biblioteca.asientos_computo' doesn't exist
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 APPPATH\Models\Principal.php(80): CodeIgniter\Database\BaseConnection->query('SELECT a.NoCuenta,
                                    a.Asiento AS AsientoTablaAsientos,
                                    ac.Asiento AS AsientoTablaAsientosComputo
                                FROM asientos a
                                    LEFT JOIN asientos_computo ac ON a.NoCuenta = ac.NoCuenta
                                WHERE a.NoCuenta = ?
                                UNION
                                SELECT ac.NoCuenta,
                                    a.Asiento AS AsientoTablaAsientos,
                                    ac.Asiento AS AsientoTablaAsientosComputo
                                FROM asientos a
                                    RIGHT JOIN asientos_computo ac ON a.NoCuenta = ac.NoCuenta
                                WHERE ac.NoCuenta = ?', [...])
 2 APPPATH\Controllers\ControllerPrincipal.php(86): App\Models\Principal->VerificarAsiento('0211980038')
 3 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\ControllerPrincipal->verificar_asiento('0211980038')
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControllerPrincipal))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-03-05 19:47:38 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in C:\xampp\htdocs\Bib\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\Bib\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', '', 'biblioteca', 3306, '', 0)
#1 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Bib\app\Models\Monitoreo.php(68): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...')
#4 C:\xampp\htdocs\Bib\app\Controllers\ControllerMonitoreo.php(58): App\Models\Monitoreo->ObtenerAsientos_hilo()
#5 C:\xampp\htdocs\Bib\system\CodeIgniter.php(942): App\Controllers\ControllerMonitoreo->ObtenerAsientos_hilo()
#6 C:\xampp\htdocs\Bib\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControllerMonitoreo))
#7 C:\xampp\htdocs\Bib\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Bib\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in C:\xampp\htdocs\Bib\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Bib\app\Models\Monitoreo.php(68): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...')
#3 C:\xampp\htdocs\Bib\app\Controllers\ControllerMonitoreo.php(58): App\Models\Monitoreo->ObtenerAsientos_hilo()
#4 C:\xampp\htdocs\Bib\system\CodeIgniter.php(942): App\Controllers\ControllerMonitoreo->ObtenerAsientos_hilo()
#5 C:\xampp\htdocs\Bib\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControllerMonitoreo))
#6 C:\xampp\htdocs\Bib\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\Bib\public\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2024-03-05 19:47:38 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Models\Monitoreo.php(68): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) as size FROM asientos')
 3 APPPATH\Controllers\ControllerMonitoreo.php(58): App\Models\Monitoreo->ObtenerAsientos_hilo()
 4 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\ControllerMonitoreo->ObtenerAsientos_hilo()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControllerMonitoreo))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-03-05 19:48:38 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in C:\xampp\htdocs\Bib\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\Bib\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', '', 'biblioteca', 3306, '', 0)
#1 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Bib\app\Models\Monitoreo.php(68): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...')
#4 C:\xampp\htdocs\Bib\app\Controllers\ControllerMonitoreo.php(58): App\Models\Monitoreo->ObtenerAsientos_hilo()
#5 C:\xampp\htdocs\Bib\system\CodeIgniter.php(942): App\Controllers\ControllerMonitoreo->ObtenerAsientos_hilo()
#6 C:\xampp\htdocs\Bib\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControllerMonitoreo))
#7 C:\xampp\htdocs\Bib\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Bib\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in C:\xampp\htdocs\Bib\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Bib\app\Models\Monitoreo.php(68): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...')
#3 C:\xampp\htdocs\Bib\app\Controllers\ControllerMonitoreo.php(58): App\Models\Monitoreo->ObtenerAsientos_hilo()
#4 C:\xampp\htdocs\Bib\system\CodeIgniter.php(942): App\Controllers\ControllerMonitoreo->ObtenerAsientos_hilo()
#5 C:\xampp\htdocs\Bib\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControllerMonitoreo))
#6 C:\xampp\htdocs\Bib\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\Bib\public\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2024-03-05 19:48:38 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Models\Monitoreo.php(68): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) as size FROM asientos')
 3 APPPATH\Controllers\ControllerMonitoreo.php(58): App\Models\Monitoreo->ObtenerAsientos_hilo()
 4 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\ControllerMonitoreo->ObtenerAsientos_hilo()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControllerMonitoreo))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-03-05 19:49:38 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in C:\xampp\htdocs\Bib\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\Bib\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', '', 'biblioteca', 3306, '', 0)
#1 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Bib\app\Models\Monitoreo.php(68): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...')
#4 C:\xampp\htdocs\Bib\app\Controllers\ControllerMonitoreo.php(58): App\Models\Monitoreo->ObtenerAsientos_hilo()
#5 C:\xampp\htdocs\Bib\system\CodeIgniter.php(942): App\Controllers\ControllerMonitoreo->ObtenerAsientos_hilo()
#6 C:\xampp\htdocs\Bib\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControllerMonitoreo))
#7 C:\xampp\htdocs\Bib\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Bib\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in C:\xampp\htdocs\Bib\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Bib\app\Models\Monitoreo.php(68): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...')
#3 C:\xampp\htdocs\Bib\app\Controllers\ControllerMonitoreo.php(58): App\Models\Monitoreo->ObtenerAsientos_hilo()
#4 C:\xampp\htdocs\Bib\system\CodeIgniter.php(942): App\Controllers\ControllerMonitoreo->ObtenerAsientos_hilo()
#5 C:\xampp\htdocs\Bib\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControllerMonitoreo))
#6 C:\xampp\htdocs\Bib\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\Bib\public\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2024-03-05 19:49:38 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Models\Monitoreo.php(68): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) as size FROM asientos')
 3 APPPATH\Controllers\ControllerMonitoreo.php(58): App\Models\Monitoreo->ObtenerAsientos_hilo()
 4 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\ControllerMonitoreo->ObtenerAsientos_hilo()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControllerMonitoreo))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-03-05 19:50:38 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in C:\xampp\htdocs\Bib\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\Bib\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', '', 'biblioteca', 3306, '', 0)
#1 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Bib\app\Models\Monitoreo.php(68): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...')
#4 C:\xampp\htdocs\Bib\app\Controllers\ControllerMonitoreo.php(58): App\Models\Monitoreo->ObtenerAsientos_hilo()
#5 C:\xampp\htdocs\Bib\system\CodeIgniter.php(942): App\Controllers\ControllerMonitoreo->ObtenerAsientos_hilo()
#6 C:\xampp\htdocs\Bib\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControllerMonitoreo))
#7 C:\xampp\htdocs\Bib\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Bib\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in C:\xampp\htdocs\Bib\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Bib\app\Models\Monitoreo.php(68): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...')
#3 C:\xampp\htdocs\Bib\app\Controllers\ControllerMonitoreo.php(58): App\Models\Monitoreo->ObtenerAsientos_hilo()
#4 C:\xampp\htdocs\Bib\system\CodeIgniter.php(942): App\Controllers\ControllerMonitoreo->ObtenerAsientos_hilo()
#5 C:\xampp\htdocs\Bib\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControllerMonitoreo))
#6 C:\xampp\htdocs\Bib\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\Bib\public\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2024-03-05 19:50:38 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Models\Monitoreo.php(68): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) as size FROM asientos')
 3 APPPATH\Controllers\ControllerMonitoreo.php(58): App\Models\Monitoreo->ObtenerAsientos_hilo()
 4 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\ControllerMonitoreo->ObtenerAsientos_hilo()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControllerMonitoreo))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-03-05 19:51:38 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in C:\xampp\htdocs\Bib\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\Bib\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', '', 'biblioteca', 3306, '', 0)
#1 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Bib\app\Models\Monitoreo.php(68): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...')
#4 C:\xampp\htdocs\Bib\app\Controllers\ControllerMonitoreo.php(58): App\Models\Monitoreo->ObtenerAsientos_hilo()
#5 C:\xampp\htdocs\Bib\system\CodeIgniter.php(942): App\Controllers\ControllerMonitoreo->ObtenerAsientos_hilo()
#6 C:\xampp\htdocs\Bib\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControllerMonitoreo))
#7 C:\xampp\htdocs\Bib\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Bib\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in C:\xampp\htdocs\Bib\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Bib\app\Models\Monitoreo.php(68): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...')
#3 C:\xampp\htdocs\Bib\app\Controllers\ControllerMonitoreo.php(58): App\Models\Monitoreo->ObtenerAsientos_hilo()
#4 C:\xampp\htdocs\Bib\system\CodeIgniter.php(942): App\Controllers\ControllerMonitoreo->ObtenerAsientos_hilo()
#5 C:\xampp\htdocs\Bib\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControllerMonitoreo))
#6 C:\xampp\htdocs\Bib\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\Bib\public\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2024-03-05 19:51:38 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Models\Monitoreo.php(68): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) as size FROM asientos')
 3 APPPATH\Controllers\ControllerMonitoreo.php(58): App\Models\Monitoreo->ObtenerAsientos_hilo()
 4 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\ControllerMonitoreo->ObtenerAsientos_hilo()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControllerMonitoreo))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-03-05 19:52:38 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in C:\xampp\htdocs\Bib\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\Bib\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', '', 'biblioteca', 3306, '', 0)
#1 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Bib\app\Models\Monitoreo.php(68): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...')
#4 C:\xampp\htdocs\Bib\app\Controllers\ControllerMonitoreo.php(58): App\Models\Monitoreo->ObtenerAsientos_hilo()
#5 C:\xampp\htdocs\Bib\system\CodeIgniter.php(942): App\Controllers\ControllerMonitoreo->ObtenerAsientos_hilo()
#6 C:\xampp\htdocs\Bib\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControllerMonitoreo))
#7 C:\xampp\htdocs\Bib\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Bib\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in C:\xampp\htdocs\Bib\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Bib\app\Models\Monitoreo.php(68): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...')
#3 C:\xampp\htdocs\Bib\app\Controllers\ControllerMonitoreo.php(58): App\Models\Monitoreo->ObtenerAsientos_hilo()
#4 C:\xampp\htdocs\Bib\system\CodeIgniter.php(942): App\Controllers\ControllerMonitoreo->ObtenerAsientos_hilo()
#5 C:\xampp\htdocs\Bib\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControllerMonitoreo))
#6 C:\xampp\htdocs\Bib\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\Bib\public\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2024-03-05 19:52:38 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Models\Monitoreo.php(68): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) as size FROM asientos')
 3 APPPATH\Controllers\ControllerMonitoreo.php(58): App\Models\Monitoreo->ObtenerAsientos_hilo()
 4 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\ControllerMonitoreo->ObtenerAsientos_hilo()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControllerMonitoreo))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-03-05 19:53:38 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in C:\xampp\htdocs\Bib\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\Bib\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', '', 'biblioteca', 3306, '', 0)
#1 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Bib\app\Models\Monitoreo.php(68): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...')
#4 C:\xampp\htdocs\Bib\app\Controllers\ControllerMonitoreo.php(58): App\Models\Monitoreo->ObtenerAsientos_hilo()
#5 C:\xampp\htdocs\Bib\system\CodeIgniter.php(942): App\Controllers\ControllerMonitoreo->ObtenerAsientos_hilo()
#6 C:\xampp\htdocs\Bib\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControllerMonitoreo))
#7 C:\xampp\htdocs\Bib\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Bib\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in C:\xampp\htdocs\Bib\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Bib\app\Models\Monitoreo.php(68): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...')
#3 C:\xampp\htdocs\Bib\app\Controllers\ControllerMonitoreo.php(58): App\Models\Monitoreo->ObtenerAsientos_hilo()
#4 C:\xampp\htdocs\Bib\system\CodeIgniter.php(942): App\Controllers\ControllerMonitoreo->ObtenerAsientos_hilo()
#5 C:\xampp\htdocs\Bib\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControllerMonitoreo))
#6 C:\xampp\htdocs\Bib\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\Bib\public\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2024-03-05 19:53:38 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Models\Monitoreo.php(68): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) as size FROM asientos')
 3 APPPATH\Controllers\ControllerMonitoreo.php(58): App\Models\Monitoreo->ObtenerAsientos_hilo()
 4 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\ControllerMonitoreo->ObtenerAsientos_hilo()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControllerMonitoreo))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-03-05 19:54:38 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in C:\xampp\htdocs\Bib\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\Bib\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', '', 'biblioteca', 3306, '', 0)
#1 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Bib\app\Models\Monitoreo.php(68): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...')
#4 C:\xampp\htdocs\Bib\app\Controllers\ControllerMonitoreo.php(58): App\Models\Monitoreo->ObtenerAsientos_hilo()
#5 C:\xampp\htdocs\Bib\system\CodeIgniter.php(942): App\Controllers\ControllerMonitoreo->ObtenerAsientos_hilo()
#6 C:\xampp\htdocs\Bib\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControllerMonitoreo))
#7 C:\xampp\htdocs\Bib\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Bib\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in C:\xampp\htdocs\Bib\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Bib\app\Models\Monitoreo.php(68): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...')
#3 C:\xampp\htdocs\Bib\app\Controllers\ControllerMonitoreo.php(58): App\Models\Monitoreo->ObtenerAsientos_hilo()
#4 C:\xampp\htdocs\Bib\system\CodeIgniter.php(942): App\Controllers\ControllerMonitoreo->ObtenerAsientos_hilo()
#5 C:\xampp\htdocs\Bib\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControllerMonitoreo))
#6 C:\xampp\htdocs\Bib\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\Bib\public\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2024-03-05 19:54:38 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Models\Monitoreo.php(68): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) as size FROM asientos')
 3 APPPATH\Controllers\ControllerMonitoreo.php(58): App\Models\Monitoreo->ObtenerAsientos_hilo()
 4 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\ControllerMonitoreo->ObtenerAsientos_hilo()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControllerMonitoreo))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-05 20:25:07 --> syntax error, unexpected variable "$idpdf"
in APPPATH\Controllers\PdfController.php on line 112.
 1 SYSTEMPATH\Autoloader\Autoloader.php(291): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs\\Bib\\app\\Controllers\\PdfController.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(269): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\PdfController')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\PdfController')
 4 SYSTEMPATH\CodeIgniter.php(900): class_exists('\\App\\Controllers\\PdfController', true)
 5 SYSTEMPATH\CodeIgniter.php(489): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-05 20:28:06 --> syntax error, unexpected variable "$idpdf"
in APPPATH\Controllers\PdfController.php on line 112.
 1 SYSTEMPATH\Autoloader\Autoloader.php(291): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs\\Bib\\app\\Controllers\\PdfController.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(269): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\PdfController')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\PdfController')
 4 SYSTEMPATH\CodeIgniter.php(900): class_exists('\\App\\Controllers\\PdfController', true)
 5 SYSTEMPATH\CodeIgniter.php(489): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-05 20:28:13 --> syntax error, unexpected variable "$idpdf"
in APPPATH\Controllers\PdfController.php on line 112.
 1 SYSTEMPATH\Autoloader\Autoloader.php(291): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs\\Bib\\app\\Controllers\\PdfController.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(269): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\PdfController')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\PdfController')
 4 SYSTEMPATH\CodeIgniter.php(900): class_exists('\\App\\Controllers\\PdfController', true)
 5 SYSTEMPATH\CodeIgniter.php(489): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-05 20:29:37 --> syntax error, unexpected variable "$idpdf"
in APPPATH\Controllers\PdfController.php on line 112.
 1 SYSTEMPATH\Autoloader\Autoloader.php(291): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs\\Bib\\app\\Controllers\\PdfController.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(269): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\PdfController')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\PdfController')
 4 SYSTEMPATH\CodeIgniter.php(900): class_exists('\\App\\Controllers\\PdfController', true)
 5 SYSTEMPATH\CodeIgniter.php(489): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-05 20:29:47 --> syntax error, unexpected variable "$idpdf"
in APPPATH\Controllers\PdfController.php on line 112.
 1 SYSTEMPATH\Autoloader\Autoloader.php(291): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs\\Bib\\app\\Controllers\\PdfController.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(269): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\PdfController')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\PdfController')
 4 SYSTEMPATH\CodeIgniter.php(900): class_exists('\\App\\Controllers\\PdfController', true)
 5 SYSTEMPATH\CodeIgniter.php(489): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-05 20:29:57 --> syntax error, unexpected variable "$idpdf"
in APPPATH\Controllers\PdfController.php on line 112.
 1 SYSTEMPATH\Autoloader\Autoloader.php(291): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs\\Bib\\app\\Controllers\\PdfController.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(269): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\PdfController')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\PdfController')
 4 SYSTEMPATH\CodeIgniter.php(900): class_exists('\\App\\Controllers\\PdfController', true)
 5 SYSTEMPATH\CodeIgniter.php(489): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-05 20:30:55 --> syntax error, unexpected variable "$idpdf"
in APPPATH\Controllers\PdfController.php on line 112.
 1 SYSTEMPATH\Autoloader\Autoloader.php(291): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs\\Bib\\app\\Controllers\\PdfController.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(269): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\PdfController')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\PdfController')
 4 SYSTEMPATH\CodeIgniter.php(900): class_exists('\\App\\Controllers\\PdfController', true)
 5 SYSTEMPATH\CodeIgniter.php(489): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-03-05 20:43:41 --> mysqli_sql_exception: Duplicate entry '0321140001' for key 'PRIMARY' in C:\xampp\htdocs\Bib\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\Bib\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO asi...', 0)
#1 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO asi...')
#2 C:\xampp\htdocs\Bib\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO asi...')
#3 C:\xampp\htdocs\Bib\app\Models\PrincipalComputo.php(21): CodeIgniter\Database\BaseConnection->query('INSERT INTO asi...', Array)
#4 C:\xampp\htdocs\Bib\app\Controllers\ControllerPrincipalComputo.php(36): App\Models\PrincipalComputo->insertarAsiento(Array)
#5 C:\xampp\htdocs\Bib\system\CodeIgniter.php(942): App\Controllers\ControllerPrincipalComputo->add()
#6 C:\xampp\htdocs\Bib\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControllerPrincipalComputo))
#7 C:\xampp\htdocs\Bib\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Bib\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2024-03-05 20:43:41 --> Duplicate entry '0321140001' for key 'PRIMARY'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 APPPATH\Models\PrincipalComputo.php(21): CodeIgniter\Database\BaseConnection->query('INSERT INTO asientos_computo VALUES (?, ?)', [...])
 2 APPPATH\Controllers\ControllerPrincipalComputo.php(36): App\Models\PrincipalComputo->insertarAsiento([...])
 3 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\ControllerPrincipalComputo->add()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ControllerPrincipalComputo))
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
